import { Toaster } from "sonner";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ApolloWrapper } from "@/ApolloWrapper";
import { UserProvider } from "@/hooks/useUser";
import { getCurrentUser } from "./(auth)/(actions)/getCurrentUser";
import { SearchedUser } from "@/typings";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Message-App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser: SearchedUser | null = await getCurrentUser();
  return (
    <html
      lang="en"
      className="scrollbar-thumb-[#696970] scrollbar-track-background"
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ApolloWrapper>
          <Toaster position="top-right" />
          <UserProvider user={currentUser}>{children}</UserProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
}
